// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBT-u_ZQb4WC_6MCvij0xw6oBn0Fzz8f2o',
    appId: '1:943667937607:web:03109afbf707a1d346cc62',
    messagingSenderId: '943667937607',
    projectId: 'fyp-2026-f41ad',
    authDomain: 'fyp-2026-f41ad.firebaseapp.com',
    storageBucket: 'fyp-2026-f41ad.firebasestorage.app',
    measurementId: 'G-5M287YJYSD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAa9j1vPcJXr2OnvJ0F75KnXaJgGPkCMZo',
    appId: '1:943667937607:android:f2fc9607c090690b46cc62',
    messagingSenderId: '943667937607',
    projectId: 'fyp-2026-f41ad',
    storageBucket: 'fyp-2026-f41ad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArjx3EgKeq9WRA4kvvvuzGHW4FMJXN05A',
    appId: '1:943667937607:ios:2a2fbad4c3605bbd46cc62',
    messagingSenderId: '943667937607',
    projectId: 'fyp-2026-f41ad',
    storageBucket: 'fyp-2026-f41ad.firebasestorage.app',
    iosBundleId: 'com.example.fyp2026',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBT-u_ZQb4WC_6MCvij0xw6oBn0Fzz8f2o',
    appId: '1:943667937607:web:7c2d93a4482f04a146cc62',
    messagingSenderId: '943667937607',
    projectId: 'fyp-2026-f41ad',
    authDomain: 'fyp-2026-f41ad.firebaseapp.com',
    storageBucket: 'fyp-2026-f41ad.firebasestorage.app',
    measurementId: 'G-8BL9EM3S17',
  );
}
